### ISSUE TITLE
Why scanning error occur? 

### ISSUE THREAD

**Issue by hyeonjae-lee09** [HCL-TECH-SOFTWARE/appscan-codesweep-action#16]
Currently, this error occur as follwing screentshot. 
but it looks like works well. 

How can i solve this problem? 

![image](https://github.com/user-attachments/assets/1b2dd892-02f7-4f36-b5df-a15d99e4a2a8)

Now I used this worksflow file. 

```
name: "HCL AppScan CodeSweep TEST"
on:
  pull_request:
    types: [opened,synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
