### ISSUE TITLE
Error when running appscan action

### ISSUE THREAD

**Issue by pietrondellamore** [HCL-TECH-SOFTWARE/appscan-codesweep-action#5]
Hey guys, 

I am facing an error when running the action for scanning my app through Github Actions.

This is the error:
![image](https://user-images.githubusercontent.com/83834671/117587885-7bc6c680-b0f6-11eb-97d5-fdc02ac2c6ab.png)

This is my action file:
```
on: [pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
    env: 
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
```
It seems to run the scan, find the issues, but can't connect into github for giving us the feedback on the PR (comment on each file that have an issue).

Have you ever faced something like that?
