### ISSUE TITLE
Error: fatal: Invalid symmetric difference expression 

### ISSUE THREAD

**Issue by khorwood** [HCL-TECH-SOFTWARE/appscan-codesweep-action#6]
When trialing this action on an existing repo, I receive the following error when running in a pull request. Am I doing something wrong, or is this a bug?

```
Checking for added files...
fatal: Invalid symmetric difference expression 2be45770d5c3e76fcd5303d51dea78879d533382...29d299fa6a0d799d8be798713f4cea7d074d2772
```

Excerpt from workflow:
```yaml
name: CodeSweep
on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
  pull_request:
    branches: [ master ]
jobs:
  scan:
    runs-on: ...
    timeout-minutes: 2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
      with:
        asoc_key: ${{secrets.ASOC_KEY}}
        asoc_secret: ${{secrets.ASOC_SECRET}}
```
